from typing import List, Dict, Any, Optional
from pydantic import BaseModel

class analyze_betting_odds_output(BaseModel):
    over_under_rates: List[float]  # List of over/under rates for each team
    point_spread_distributions: List[float]  # List of point spread distributions for each team
    trends_and_patterns: str  # Description of trends and patterns identified in the betting odds data
    insights: str  # Insights on the betting odds, including recommendations
    is_data_valid: bool  # Whether the data is valid for analysis

class calculate_team_performance_metrics_output(BaseModel):
    team_names: List[str]  # List of NFL team names
    win_rates: List[float]  # List of win rates for each team, ranging from 0 to 1
    points_scored: List[int]  # List of points scored by each team
    points_allowed: List[int]  # List of points allowed by each team
    yards_gained: List[int]  # List of yards gained by each team

class clean_and_process_data_output(BaseModel):
    cleaned_teams_data: List[str]  # List of cleaned team names
    processed_win_loss_records: List[str]  # List of processed win-loss records
    cleaned_points_scored: List[float]  # List of cleaned points scored
    cleaned_odds: List[float]  # List of cleaned betting odds
    processed_point_spreads: List[float]  # List of processed point spreads
    cleaned_over_unders: List[float]  # List of cleaned over/unders
    data_is_valid: bool  # Whether the cleaned data is valid

class collect_betting_odds_data_output(BaseModel):
    teams: List[str]  # List of NFL team names
    point_spreads: List[float]  # List of point spreads corresponding to each team
    moneylines: List[float]  # List of moneyline odds corresponding to each team
    over_unders: List[float]  # List of over/under odds corresponding to each team

class collect_nfl_teams_data_output(BaseModel):
    team_name: str  # Name of the NFL team
    win_loss_record: str  # Win-loss record of the team (e.g., 10-5)
    points_scored: int  # Total points scored by the team
    standings: str  # Current standings of the team (e.g., 1st in division)
    statistics: str  # List of additional statistics for the team (e.g., passing yards, rushing yards, etc.)

class generate_insights_output(BaseModel):
    recommended_teams_to_bet_on: List[str]  # List of team names recommended to bet on
    recommended_teams_to_avoid: List[str]  # List of team names recommended to avoid betting on
    top_performing_teams: List[str]  # List of top performing team names based on metrics
    worst_performing_teams: List[str]  # List of worst performing team names based on metrics
    betting_odds_trends: str  # Summary of trends and patterns in betting odds
    over_under_insights: str  # Insights on over/under rates
    point_spread_distribution: str  # Distribution of point spreads

class visualize_results_output(BaseModel):
    visualization_type: str  # Type of visualization (e.g., chart, graph, table)
    team_performance_metrics: List[float]  # List of team performance metrics (e.g., win rates, points scored)
    betting_odds_trends: List[str]  # List of trends and patterns in betting odds
    insights_summary: str  # Summary of the insights generated by the analysis
    recommendations: List[str]  # List of recommendations on which teams to bet on and which to avoid

