# -- PRD --
# 1. BULLET: Retrieve historical market data for the S&P500 index from the parent node
#   'collect_market_data'
#   Reason: To backtest the trading strategy, we need historical market data
#   Impact: HIGH
#   Complexity: LOW
#   Method: Use the output of 'collect_market_data' node, which provides market data
#           points including open, high, low, and close prices
# 
# -----------------------------------------------------------------------------
# 2. BULLET: Get trading signals generated by the selected alpha model from the parent
#   node 'generate_trading_signals'
#   Reason: Trading signals are necessary to determine when to buy or sell the S&P500
#           index
#   Impact: HIGH
#   Complexity: LOW
#   Method: Use the output of 'generate_trading_signals' node, which provides signal
#           timestamps, signal types, and signal prices
# 
# -----------------------------------------------------------------------------
# 3. BULLET: Calculate the return of the trading strategy by applying the trading signals
#   to the historical market data
#   Reason: The return of the trading strategy is a key performance metric
#   Impact: HIGH
#   Complexity: MEDIUM
#   Method: Use the trading signals and market data to simulate trades and calculate
#           the return
# 
# -----------------------------------------------------------------------------
# 4. BULLET: Calculate the risk of the trading strategy using metrics such as volatility
#   or drawdown
#   Reason: The risk of the trading strategy is a key performance metric
#   Impact: HIGH
#   Complexity: MEDIUM
#   Method: Use the trading signals and market data to calculate the risk metrics
# 
# -----------------------------------------------------------------------------
# 5. BULLET: Calculate the Sharpe ratio of the trading strategy using the return and risk
#   metrics
#   Reason: The Sharpe ratio is a key performance metric that balances return and risk
#   Impact: HIGH
#   Complexity: MEDIUM
#   Method: Use the return and risk metrics to calculate the Sharpe ratio
# 
# -----------------------------------------------------------------------------
# 6. BULLET: Determine whether the trading strategy is valid based on the backtest results
#   Reason: The validity of the trading strategy is crucial for further refinement and
#           deployment
#   Impact: HIGH
#   Complexity: LOW
#   Method: Use the performance metrics to determine whether the strategy is valid
# -- END PRD --

from pydantic import BaseModel, Field
from typing import List


class GenerateTradingSignalsOutput(BaseModel):
    """Pydantic model for generate_trading_signals node outputs."""
    signal_timestamps: List[str] = Field(..., description="List of timestamps when trading signals were generated")
    signal_types: List[str] = Field(..., description="List of signal types (buy or sell)")
    signal_prices: List[float] = Field(..., description="List of prices at which the signals were generated")
    is_valid: bool = Field(..., description="Whether the generated signal is valid")


class BacktestTradingStrategyOutput(BaseModel):
    """Pydantic model for backtest_trading_strategy node outputs."""
    backtest_return: float = Field(..., description="The return of the trading strategy")
    backtest_risk: float = Field(..., description="The risk of the trading strategy")
    sharpe_ratio: float = Field(..., description="The Sharpe ratio of the trading strategy")
    performance_metrics: List[str] = Field(..., description="List of additional performance metrics")
    is_strategy_valid: bool = Field(..., description="Whether the trading strategy is valid based on the backtest results")


def backtest_trading_strategy(generate_trading_signals_input: GenerateTradingSignalsOutput, **kwargs) -> BacktestTradingStrategyOutput:
    """Backtest the trading strategy using historical data

    Args:
        generate_trading_signals_input: Input from the 'generate_trading_signals' node.
        **kwargs: Additional keyword arguments.

    Returns:
        BacktestTradingStrategyOutput: Object containing outputs for this node.
    """
    # TODO: Implement this function

    # Return stub output with placeholder values
    return BacktestTradingStrategyOutput(
        backtest_return=0.0,
        backtest_risk=0.0,
        sharpe_ratio=0.0,
        performance_metrics=[],
        is_strategy_valid=False,
    )